// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kldmnqimwqqyqtssmngz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZG1ucWltd3FxeXF0c3Ntbmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzM5NTQsImV4cCI6MjA1NjYwOTk1NH0.QrHxmEg594ZumxEjHnOdcaeloH0aXEBOlybx43DSqB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);